---
# tasks file for javajdk
- name: env
  include_vars: "{{ ansible_distribution }}.yaml"

- include_tasks: centos8.yaml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "8"

- include_tasks: centos7.yaml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7"


