---
# tasks file for postgresql

- name: 创建docker解压目录
  file:
    path: "{{ docker_app }}"
    state: directory

- name: 传送docker二进制包到主机
  copy:
    src: "{{ docker_package }}"
    dest: "{{ docker_dw }}"
    # 仅当目标目录不存在文件时才会传送文件
    force: no
    owner: root
    group: root

- name: 解压docker二进制包
  unarchive:
    src: "{{ docker_dw }}/{{ docker_package }}"
    dest: "{{ docker_app }}"
    owner: root
    group: root
    mode: 751
    # 表示文件如果已经存在，就不会继续上传
    keep_newer: yes
    # 表示需要解压的文件已经存在在远端，而不是在控制节点
    remote_src: yes

- name: 拷贝docker二进制文件
  copy:
    src: "{{ docker_app }}/docker"
    dest: "{{ docker_us }}"
    owner: foo
    group: foo
    mode: '0644'
    remote_src: yes
